config/routes.rb
WindowsSampleApp::Application.routes.draw do
  get "users/new"
  root "static_pages#home"
	match '/signup', to: 'users#new', via: 'get'
	match '/help', to: 'static_pages#help', via: 'get'
	match '/about', to: 'static_pages#about', via: 'get'
	match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

	def contact
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# ページごとの完全なタイトルを返します。
	def full_title(page_title)
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.slim
footer.footer
  small
    a> href="http://railstutorial.jp/" Rails Tutorial
    | by Michael Hartl

  nav
    ul
      li
        == link_to "About", about_path
      li
        == link_to "Contact", contact_path
      li
        a href="http://news.railstutorial.jp/" News

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      == link_to "sample app", root_path, id: "logo"
      nav
        ul.nav.navbar-nav.pull-right
          li
            == link_to "Home", root_path
          li
            == link_to "Help", help_path
          li
            == link_to "Sign in", '#'

app/views/layouts/_shim.html.slim
/![if lt IE 9]>
  <script src=http://html5shim.googlecode.com/svn/trunk/html5.js></script>
  <![endif]

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      == full_title(yield(:title))
    == stylesheet_link_tag 'application',  media: 'all', 'data-turbolinks-track' => true
    == javascript_include_tag 'application',  media: 'all', 'data-turbolinks-track' => true
    == csrf_meta_tags
    == render 'layouts/shim'

  body
    == render 'layouts/header'
    .container
      == yield
      == render 'layouts/footer'

app/views/static_pages/about.html.slim
- provide(:title, 'About Us')
h1 About Us
p
  | The
  a<> href="http://railstutorial.org/" Ruby on Rails Tutorial
  | is a project to make a book and screencasts to teach web development with
  a< href="http://railstutorial.org/" Ruby on Rails
  | .
  | This is the sample application for the tutorial.

app/views/static_pages/contact.html.slim
== provide(:title, 'Contact')
h1 Contact
p
  | Contact Ruby on Rails Tutorial about the sample app at the
  a< href="http://railstutorial.jp/contact" contact page
  | .

app/views/static_pages/help.html.slim
- provide(:title, 'Help')
h1 Help
p
  | Get help on the Ruby on Rails Tutorial at the
  a< href="http://railstutorial.jp/" Rails Tutorial help page
  | . 
  | To get help on this sample app, see the
  a< href="http://railstutorial.jp/book" Rails Tutorial Book
  | .

app/views/static_pages/home.html.slim
.center.jumbotron
  h1 Welcome to the Sample App

  h2
    | This is the home page for the 
    a> href="http://railstutorial.jp/" Ruby on Rails Tutorial
    | sample application.

  == link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"

== link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrailis.org/'

app/views/users/new.html.slim
== provide(:title, 'Sign up')
h1 Sign up
p Find me in app/views/users/new.html.slim